-- MySQL Script generated by MySQL Workbench
-- 03/24/18 19:43:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProduExpiraGame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProduExpiraGame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProduExpiraGame` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ProduExpiraGame` ;

-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`usuario` (
  `id` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`badge` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_badge_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_badge_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ProduExpiraGame`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`pontuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`pontuacao` (
  `id` INT NOT NULL,
  `pontos` INT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_pontuacao_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_pontuacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ProduExpiraGame`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`conquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`conquista` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_conquista_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_conquista_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ProduExpiraGame`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`armazenamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`armazenamento` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`produto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `valor` FLOAT NULL,
  `data_fabricacao` DATE NULL,
  `data_vencimento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`cliente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` INT NULL,
  `` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  `armazenamento_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `armazenamento_id`, `produto_id`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_cliente_armazenamento1_idx` (`armazenamento_id` ASC),
  INDEX `fk_cliente_produto1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ProduExpiraGame`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_armazenamento1`
    FOREIGN KEY (`armazenamento_id`)
    REFERENCES `ProduExpiraGame`.`armazenamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ProduExpiraGame`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`fornecedor` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cnpj` INT(13) NULL,
  `armazenamento_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `armazenamento_id`, `produto_id`),
  INDEX `fk_fornecedor_armazenamento1_idx` (`armazenamento_id` ASC),
  INDEX `fk_fornecedor_produto1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_fornecedor_armazenamento1`
    FOREIGN KEY (`armazenamento_id`)
    REFERENCES `ProduExpiraGame`.`armazenamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ProduExpiraGame`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`promocao` (
  `id` INT NOT NULL,
  `data_promocao` DATE NULL,
  `desconto` INT NULL,
  `nome` VARCHAR(45) NULL,
  `pontuacao` INT NULL,
  `fornecedor_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fornecedor_id`, `produto_id`, `cliente_id`),
  INDEX `fk_promocao_fornecedor1_idx` (`fornecedor_id` ASC),
  INDEX `fk_promocao_produto1_idx` (`produto_id` ASC),
  INDEX `fk_promocao_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_promocao_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `ProduExpiraGame`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promocao_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ProduExpiraGame`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promocao_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ProduExpiraGame`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`estado_consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`estado_consumo` (
  `id` INT NOT NULL,
  `situacao` VARCHAR(45) NULL,
  `diferenca_prazo_consumo` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`monitor_consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`monitor_consumo` (
  `id` INT NOT NULL,
  `estado_consumo_id` INT NOT NULL,
  `armazenamento_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `estado_consumo_id`, `armazenamento_id`, `produto_id`),
  INDEX `fk_monitor_consumo_armazenamento1_idx` (`armazenamento_id` ASC),
  INDEX `fk_monitor_consumo_produto1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_monitor_consumo_estado_consumo1`
    FOREIGN KEY (`estado_consumo_id`)
    REFERENCES `ProduExpiraGame`.`estado_consumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitor_consumo_armazenamento1`
    FOREIGN KEY (`armazenamento_id`)
    REFERENCES `ProduExpiraGame`.`armazenamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitor_consumo_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ProduExpiraGame`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProduExpiraGame`.`alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProduExpiraGame`.`alerta` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `data_expiracao` DATE NOT NULL,
  `monitor_consumo_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `monitor_consumo_id`, `usuario_id`),
  INDEX `fk_alerta_monitor_consumo1_idx` (`monitor_consumo_id` ASC),
  INDEX `fk_alerta_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_alerta_monitor_consumo1`
    FOREIGN KEY (`monitor_consumo_id`)
    REFERENCES `ProduExpiraGame`.`monitor_consumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alerta_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ProduExpiraGame`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
